/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphs;

import com.sun.awt.AWTUtilities;
import model.Jugador;

/**
 *
 * @author GabrielGiancarlo
 */
public class Ventana1vsPc_Niveles extends javax.swing.JFrame {
    Jugador jugador;
    /**
     * Creates new form VentanaPrincipal
     */
      
    public void botonTransparente(){ 
        botonExit.setOpaque(false);
        botonExit.setContentAreaFilled(false);
        botonExit.setBorderPainted(false);
        
        botonNivelFacil.setOpaque(false);
        botonNivelFacil.setContentAreaFilled(false);
        botonNivelFacil.setBorderPainted(false);
        
        botonNivelMedio.setOpaque(false);
        botonNivelMedio.setContentAreaFilled(false);
        botonNivelMedio.setBorderPainted(false);
        
        botonNivelDificil.setOpaque(false);
        botonNivelDificil.setContentAreaFilled(false);
        botonNivelDificil.setBorderPainted(false);
        
        botonAtras.setOpaque(false);
        botonAtras.setContentAreaFilled(false);
        botonAtras.setBorderPainted(false);
        
    }
    
    public Ventana1vsPc_Niveles(Jugador jugador) {
        this.jugador = jugador;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        
        System.out.println(jugador.getNombre());
        this.botonTransparente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonNivelMedio = new javax.swing.JButton();
        botonNivelDificil = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonNivelFacil = new javax.swing.JButton();
        botonExit = new javax.swing.JButton();
        FondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TresEnRaya_2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        botonNivelMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelMedio_1.png"))); // NOI18N
        botonNivelMedio.setBorder(null);
        botonNivelMedio.setBorderPainted(false);
        botonNivelMedio.setContentAreaFilled(false);
        botonNivelMedio.setFocusPainted(false);
        botonNivelMedio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNivelMedio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelMedio_3.png"))); // NOI18N
        botonNivelMedio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelMedio_2.png"))); // NOI18N
        botonNivelMedio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelMedio_3.png"))); // NOI18N
        botonNivelMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNivelMedioActionPerformed(evt);
            }
        });
        getContentPane().add(botonNivelMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 260, 63));

        botonNivelDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelDificil_1.png"))); // NOI18N
        botonNivelDificil.setBorder(null);
        botonNivelDificil.setBorderPainted(false);
        botonNivelDificil.setContentAreaFilled(false);
        botonNivelDificil.setFocusPainted(false);
        botonNivelDificil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNivelDificil.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelDificil_3.png"))); // NOI18N
        botonNivelDificil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelDificil_2.png"))); // NOI18N
        botonNivelDificil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelDificil_3.png"))); // NOI18N
        botonNivelDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNivelDificilActionPerformed(evt);
            }
        });
        getContentPane().add(botonNivelDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 260, 63));

        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras_1.png"))); // NOI18N
        botonAtras.setBorder(null);
        botonAtras.setBorderPainted(false);
        botonAtras.setContentAreaFilled(false);
        botonAtras.setFocusPainted(false);
        botonAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras_3.png"))); // NOI18N
        botonAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras_2.png"))); // NOI18N
        botonAtras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras_3.png"))); // NOI18N
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 110, 30));

        botonNivelFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelFacil_1.png"))); // NOI18N
        botonNivelFacil.setBorder(null);
        botonNivelFacil.setBorderPainted(false);
        botonNivelFacil.setContentAreaFilled(false);
        botonNivelFacil.setFocusPainted(false);
        botonNivelFacil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNivelFacil.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelFacil_3.png"))); // NOI18N
        botonNivelFacil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelFacil_2.png"))); // NOI18N
        botonNivelFacil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNivelFacil_3.png"))); // NOI18N
        botonNivelFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNivelFacilActionPerformed(evt);
            }
        });
        getContentPane().add(botonNivelFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 260, 63));

        botonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exitB.png"))); // NOI18N
        botonExit.setBorder(null);
        botonExit.setBorderPainted(false);
        botonExit.setContentAreaFilled(false);
        botonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exitB3_2.png"))); // NOI18N
        botonExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exitB2.png"))); // NOI18N
        botonExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exitB3_2.png"))); // NOI18N
        botonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExitActionPerformed(evt);
            }
        });
        getContentPane().add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 35, 25, 25));

        FondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo2.png"))); // NOI18N
        getContentPane().add(FondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonExitActionPerformed

    private void botonNivelMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNivelMedioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        new Ventana1vsPc_Nivel_Medio().setVisible(true); 
    }//GEN-LAST:event_botonNivelMedioActionPerformed

    private void botonNivelDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNivelDificilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        new Ventana1vsPc_Nivel_Dificil(jugador).setVisible(true);
    }//GEN-LAST:event_botonNivelDificilActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        new VentanaPrincipal().setVisible(true);
        
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonNivelFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNivelFacilActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        new Ventana1vsPc_Nivel_Facil().setVisible(true);
        
    }//GEN-LAST:event_botonNivelFacilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1vsPc_Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1vsPc_Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1vsPc_Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1vsPc_Niveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jugador jugador = null;
                new Ventana1vsPc_Niveles(jugador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPrincipal;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonExit;
    private javax.swing.JButton botonNivelDificil;
    private javax.swing.JButton botonNivelFacil;
    private javax.swing.JButton botonNivelMedio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
